package com.sdkwork.app

data class ImageGenerationForm(
    val title: String? = null,
    val prompt: String? = null,
    val negativePrompt: String? = null,
    val model: String? = null,
    val channel: String? = null,
    val referenceAssets: List<AssetMediaResource>? = null,
    val n: Int? = null,
    val seed: Int? = null,
    val async: Boolean? = null,
    val callbackUrl: String? = null,
    val extraParams: Map<String, Any>? = null,
    val bizScene: String? = null,
    val bizId: Int? = null,
    val conversationId: Int? = null,
    val messageId: Int? = null,
    val width: Int? = null,
    val height: Int? = null,
    val size: String? = null,
    val quality: String? = null,
    val style: String? = null,
    val format: String? = null,
    val cfgScale: Double? = null,
    val steps: Int? = null,
    val sampler: String? = null,
    val strength: Double? = null,
    val maskAssets: List<AssetMediaResource>? = null,
    val safetyChecker: Boolean? = null,
    val aspectRatio: String? = null,
    val type: String? = null,
    val referenceAssetCount: Int? = null
)
