package com.sdkwork.app

data class MusicGenerationForm(
    val title: String? = null,
    val prompt: String? = null,
    val negativePrompt: String? = null,
    val model: String? = null,
    val channel: String? = null,
    val referenceAssets: List<AssetMediaResource>? = null,
    val n: Int? = null,
    val seed: Int? = null,
    val async: Boolean? = null,
    val callbackUrl: String? = null,
    val extraParams: Map<String, Any>? = null,
    val bizScene: String? = null,
    val bizId: Int? = null,
    val conversationId: Int? = null,
    val messageId: Int? = null,
    val lyrics: String? = null,
    val duration: Int? = null,
    val genre: String? = null,
    val style: String? = null,
    val tempo: Int? = null,
    val key: String? = null,
    val mood: String? = null,
    val instruments: String? = null,
    val format: String? = null,
    val type: String? = null,
    val referenceAssetCount: Int? = null
)
