package com.sdkwork.app.api

import com.sdkwork.app.http.HttpClient

/**
 * API modules for sdkwork-app-sdk
 */
class Api(private val client: HttpClient) {
    val workspaces: WorkspacesApi = WorkspacesApi(client)
    val voiceSpeaker: VoiceSpeakerApi = VoiceSpeakerApi(client)
    val video: VideoApi = VideoApi(client)
    val user: UserApi = UserApi(client)
    val tool: ToolApi = ToolApi(client)
    val tenant: TenantApi = TenantApi(client)
    val social: SocialApi = SocialApi(client)
    val skill: SkillApi = SkillApi(client)
    val shops: ShopsApi = ShopsApi(client)
    val share: ShareApi = ShareApi(client)
    val settings: SettingsApi = SettingsApi(client)
    val ai: AiApi = AiApi(client)
    val projects: ProjectsApi = ProjectsApi(client)
    val products: ProductsApi = ProductsApi(client)
    val partner: PartnerApi = PartnerApi(client)
    val notification: NotificationApi = NotificationApi(client)
    val notes: NotesApi = NotesApi(client)
    val news: NewsApi = NewsApi(client)
    val music: MusicApi = MusicApi(client)
    val knowledgeDocuments: KnowledgeDocumentsApi = KnowledgeDocumentsApi(client)
    val invoice: InvoiceApi = InvoiceApi(client)
    val image: ImageApi = ImageApi(client)
    val style: StyleApi = StyleApi(client)
    val fileSystem: FileSystemApi = FileSystemApi(client)
    val feedback: FeedbackApi = FeedbackApi(client)
    val favorite: FavoriteApi = FavoriteApi(client)
    val drive: DriveApi = DriveApi(client)
    val documents: DocumentsApi = DocumentsApi(client)
    val dashboard: DashboardApi = DashboardApi(client)
    val collection: CollectionApi = CollectionApi(client)
    val chat: ChatApi = ChatApi(client)
    val character: CharacterApi = CharacterApi(client)
    val category: CategoryApi = CategoryApi(client)
    val cart: CartApi = CartApi(client)
    val assets: AssetsApi = AssetsApi(client)
    val app: AppApi = AppApi(client)
    val announcement: AnnouncementApi = AnnouncementApi(client)
    val agent: AgentApi = AgentApi(client)
    val advert: AdvertApi = AdvertApi(client)
    val wallet: WalletApi = WalletApi(client)
    val vote: VoteApi = VoteApi(client)
    val vip: VipApi = VipApi(client)
    val upload: UploadApi = UploadApi(client)
    val search: SearchApi = SearchApi(client)
    val rtc: RtcApi = RtcApi(client)
    val payments: PaymentsApi = PaymentsApi(client)
    val organization: OrganizationApi = OrganizationApi(client)
    val orders: OrdersApi = OrdersApi(client)
    val model: ModelApi = ModelApi(client)
    val history: HistoryApi = HistoryApi(client)
    val soundEffect: SoundEffectApi = SoundEffectApi(client)
    val generation: GenerationApi = GenerationApi(client)
    val audio: AudioApi = AudioApi(client)
    val feed: FeedApi = FeedApi(client)
    val currency: CurrencyApi = CurrencyApi(client)
    val coupons: CouponsApi = CouponsApi(client)
    val comments: CommentsApi = CommentsApi(client)
    val auth: AuthApi = AuthApi(client)
    val audit: AuditApi = AuditApi(client)
    val analytics: AnalyticsApi = AnalyticsApi(client)
    val agentMemory: AgentMemoryApi = AgentMemoryApi(client)
    val activity: ActivityApi = ActivityApi(client)
    val account: AccountApi = AccountApi(client)
    val ab: AbApi = AbApi(client)
    val sku: SkuApi = SkuApi(client)
}
